version: "3.8"

services:
  station:
    build: .
    container_name: station
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: >
      sh -c "celery -A rick_and_morty_api worker --loglevel=INFO"
    restart: always
    depends_on:
      - redis


  pgdb:
    image: postgres:alpine
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'

volumes:
  pgdata:
